l=[]
l.append(1)
l.append(2)
l.append(3)
l.append(4)
l.append(5)
l.append(6)
l.append(7)
l.append(8)
l.append(9)
l.append(10)
print(l)
ind=int(input("Enter position to insert:"))
ele=int(input("Enter element to insert:"))
l.insert(ind,ele)
print(l)
