print(type(10.5))
x=10.5
print(int(x))
print(complex(x))
print(bool(x))
y=10+2j
print(type(y))
#print(int(y)) NOTE:complex data type cannot converted into float and integer datatype
#print(float(y))
print(bool(y))
z=False
print(type(z))
print(int(z))
print(float(z))
print(complex(z))
a=True
print(type(a))
print(int(a))
print(float(a))
print(complex(a))